# Generated by Django 2.0 on 2022-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='adscription',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
