# Generated by Selenium IDE
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from base.tests import BaseTestCase
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.auth.models import User

class TestCreatenuevouser(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()

    options = webdriver.ChromeOptions()
    options.headless = False
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}

    user_superuser = User(username='superadmin', is_staff=True, is_superuser=True)
    user_superuser.set_password('qwerty')
    user_superuser.save()

    super().setUp() 
  
  def tearDown(self):
    self.driver.quit()
    super().tearDown()
  
  def test_createnuevouser(self):
    self.driver.get(f'{self.live_server_url}/admin/')
    
    self.driver.find_element(By.ID,'id_username').send_keys("superadmin")
    self.driver.find_element(By.ID,'id_password').send_keys("qwerty",Keys.ENTER)
    time.sleep(2)

    self.driver.set_window_size(1440, 752)
    self.driver.find_element(By.CSS_SELECTOR, ".model-user .addlink").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("nuevouser")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("esteesunnuevousuario")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("esteesunnuevousuario")
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.ID, "id_first_name").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("Nuevo")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.driver.find_element(By.ID, "id_last_name").send_keys("Usuario")
    self.driver.find_element(By.NAME, "_save").click()
  
